- name: Include prepare.yml
  ansible.builtin.import_playbook: prepare.yml

- name: Include setup.yml
  ansible.builtin.import_playbook: setup.yml

- name: Include deploy.yml
  ansible.builtin.import_playbook: deploy.yml
